require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Disabled to drop Flipper's OpenSSL-Universal 1.1.1100 transitive dependency.
# Flipper is debug-only and is not used by Chargebee IAP.
flipper_config = FlipperConfiguration.disabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'ChargebeeReactNativeExample' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ChargebeeReactNativeExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Yoga (RN 0.71) compiles with -Werror and declares `operator"" _pt`, which
    # clang 18+ (Xcode 16 and newer) rejects as -Wdeprecated-literal-operator.
    installer.pods_project.targets.each do |target|
      next unless target.name == 'Yoga'
      target.source_build_phase.files.each do |file|
        settings = file.settings
        next unless settings && settings['COMPILER_FLAGS']
        settings['COMPILER_FLAGS'] = settings['COMPILER_FLAGS'].gsub(/\s*-Werror\b/, '')
        file.settings = settings
      end
    end
    installer.pods_project.save
  end
end
