package com.chargebee.android.models

enum class CBReactNativeError(val code: Int) {
  UNKNOWN(0),
  INVALID_SDK_CONFIGURATION(1),
  INVALID_CATALOG_VERSION(2),
  INVALID_CLIENT(3),
  INVALID_OFFER(4),
  INVALID_PRICE(5),
  INVALID_PROMO_CODE(6),
  INVALID_PROMO_OFFER(7),
  INVALID_PURCHASE(8),
  INVALID_SANDBOX(9),
  NETWORK_CONNECTION_FAILED(10),
  PAYMENT_FAILED(11),
  PAYMENT_NOT_ALLOWED(12),
  PRIVACY_ACKNOWLEDGEMENT_REQUIRED(13),
  PRODUCT_NOT_AVAILABLE(14),
  CANNOT_MAKE_PAYMENTS(15),
  INVALID_CUSTOMER_ID(16),
  INVALID_SDK_KEY(17),
  NO_PRODUCT_TO_RESTORE(18),
  PRODUCT_ID_NOT_FOUND(19),
  PRODUCTS_NOT_FOUND(20),
  SK_REQUEST_FAILED(21),
  USER_CANCELLED(22),
  RESOURCE_NOT_FOUND(23),
  SYSTEM_ERROR(100);
}
