name: Build React Native
on:
  push: 
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Yarn Install
        run: yarn intsall
      - name: Yarn Tests
        run: yarn test
      - name: Linter
        run: yarn run tslint